routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/register', function () {
    return redirect(route('home'));
})->name('register');

Route::get('/', 'HomeController@index')->name('home');
Route::resource('order', 'OrderController');
Route::resource('product', 'ProductController');

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $fillable = [
        'firstname',
        'lastname',
        'city',
        'address',
        'email',
        'phone',
        'additionalinfo'
    ];
}

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    public static function uploadImage($image, $title)
    {
        if (!file_exists(public_path('uploads'))) {
            mkdir(public_path('uploads'));
        }

        $image->move(public_path('uploads'), $title);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Product;

class HomeController extends Controller
{
    /**
     * Show the application dashboard.
     *
     * @param Product $product
     * @return \Illuminate\Http\Response
     */
    public function index(Product $product)
    {
        return view('home', ['product' =>  $product->firstOrFail()]);
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Order;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class OrderController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->only(array('index', 'show'));
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = DB::table('orders')->paginate(15);

        return view('orders.index', ['orders' => $orders]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'firstname' => 'required',
            'lastname' => 'required',
            'city' => 'required|min:2',
            'address' => 'required|min:2',
            'phone' => 'required|regex:/^\+?([0-9]{1,4})\)?[-. ]?([0-9]{10})$/',
            'email' => 'required|email'
        ]);

        $order = new Order();
        $order->fill($request->all());
        $order->save();

        return redirect(route('home'))->with('status', 'Order placed successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Order $order
     * @return \Illuminate\Http\Response
     */
    public function show(Order $order)
    {
        return view('orders.show', ['order' => $order]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Order $order
     * @return \Illuminate\Http\Response
     */
    public function update(Order $order)
    {
        if ($order->status !== 1) {
            $order->status = 1;
            $order->update();
        } else {
            return redirect()->back()->with('order_warning', 'Order is already complete.');
        }

        return redirect()->back();
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('products.edit', ['product' => $product->firstOrFail()]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Product $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $request->validate([
            'name' => 'required|min:2',
            'price' => 'required|numeric',
            'description' => 'required',
            'image' => 'mimes:jpeg,bmp,png|max:2048'
        ]);

        $imgTitle = time() . '.' . $request->image->getClientOriginalExtension();

        Product::uploadImage($request->image, $imgTitle);

        $product->name = $request->name;
        $product->price = $request->price;
        $product->description = $request->description;
        $product->image = url('uploads') . '/' . $imgTitle;
        $product->update();

        return redirect()->back()->with('status', 'Product updated successfully!');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-10 col-lg-offset-1">
                @if (session('status'))
                    <div class="alert alert-success">
                        {{ session('status') }}
                    </div>
                @endif
                <div class="row">
                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                        <img src="{{ $product->image }}" class="img-responsive" alt="{{ $product->name }}">
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                        <h1>{{ $product->name }}</h1>

                        <h2>{{ number_format($product->price, 2, '.', '') }} &euro;</h2>

                        <p>
                            {{ $product->description }}
                        </p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <h2>Order form</h2>

                        <div class="panel panel-default">
                            <div class="panel-body">
                                @if($errors->any())
                                    <div class="alert alert-danger">
                                        <ul>
                                            @foreach ($errors->all() as $error)
                                                <li>{{ $error }}</li>
                                            @endforeach
                                        </ul>
                                    </div>
                                @endif
                                <form method="POST" action="{{ route('order.store') }}">
                                    {{ csrf_field() }}
                                    <div class="row">
                                        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                                            <div class="form-group">
                                                <label for="first_name">First name</label>
                                                <input type="text" class="form-control" id="first_name"
                                                       name="firstname" value="{{ old('firstname') }}">
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                                            <div class="form-group">
                                                <label for="last_name">Last name</label>
                                                <input type="text" class="form-control" id="last_name"
                                                       name="lastname" value="{{ old('lastname') }}">
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                                            <div class="form-group">
                                                <label for="city">City</label>
                                                <input type="text" class="form-control" id="city" name="city"
                                                       value="{{ old('city') }}">
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                                            <div class="form-group">
                                                <label for="address">Address</label>
                                                <input type="text" class="form-control" id="address" name="address"
                                                       value="{{ old('address') }}">
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                                            <div class="form-group">
                                                <label for="email">Email</label>
                                                <input type="email" class="form-control" id="email" name="email"
                                                       value="{{ old('email') }}">
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                                            <div class="form-group">
                                                <label for="phone">Phone</label>
                                                <input type="tel" class="form-control" id="phone" name="phone"
                                                       value="{{ old('phone') }}">
                                            </div>
                                        </div>
                                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                            <div class="form-group">
                                                <label for="additional_info">Additional information</label>
                                                    <textarea class="form-control" rows="5" id="additionalinfo"
                                                              name="additionalinfo">{{ old('additionalinfo') }}</textarea>
                                            </div>
                                        </div>
                                        <div class="col-sm-6 col-md-4 col-lg-4 col-sm-offset-3 col-md-offset-4 col-lg-offset-4">
                                            <button type="submit"
                                                    class="btn btn-success btn-lg btn-block pull-right">
                                                Order
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/bootstrap.css') }}" rel="stylesheet">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
            </div>

            <div id="app-navbar-collapse" class="navbar-collapse collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    <li><a href="{{ route('home') }}">Home</a></li>
                    @auth
                    <li><a href="{{ route('order.index') }}">Orders</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-expanded="false">
                            Product <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{{ route('product.edit', \App\Product::firstOrFail()) }}">Edit</a></li>
                        </ul>
                    </li>
                    @endauth
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @guest
                    <li><a href="{{ route('login') }}">Login</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        Logout
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                          style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                            </ul>
                        </li>
                        @endguest
                </ul>
            </div>
        </div>
    </nav>

    @yield('content')
</div>

<!-- Scripts -->
<script src="{{ asset('js/jquery.min.js') }}"></script>
<script src="{{ asset('js/app.js') }}"></script>
<script src="{{ asset('js/bootstrap.js') }}"></script>
</body>
</html>

resources/views/orders/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                @if(count($orders) > 0)
                    <div class="panel panel-default">
                        <table id="orders_table" class="table table-striped table-responsive">
                            <thead>
                            <tr>
                                <th class="text-center">ID</th>
                                <th>Name</th>
                                <th>Address</th>
                                <th>Email</th>
                                <th>Phone</th>
                                <th class="text-center">Status</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($orders as $order)
                                <tr data-href="{{ route('order.show', [$order->id]) }}">
                                    <td class="text-center">{{ $order->id }}</td>
                                    <td>{{ $order->firstname }} {{ $order->lastname }}</td>
                                    <td>{{ $order->address }}, {{ $order->city }}</td>
                                    <td>{{ $order->email }}</td>
                                    <td>{{ $order->phone }}</td>
                                    <td class="text-center">
                                        <div class="label label-{{ $order->status == 1 ? 'success' : 'default' }}">
                                            {{ $order->status == 1 ? 'Complete' : 'Incomplete' }}
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    {{ $orders->links() }}
                @else
                    <p class="text-center">No orders yet.</p>
                @endif
            </div>
        </div>
    </div>
@endsection

resources/views/orders/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-4 col-md-offset-3 col-lg-offset-4">
                @if (session('order_warning'))
                    <div class="alert alert-warning">
                        {{ session('order_warning') }}
                    </div>
                @endif
                <div class="panel {{ $order->status == 1 ? 'panel-success' : 'panel-default' }}">
                    @if($order->status == 1)
                        <div class="panel-heading">Complete</div>
                    @endif
                    <div class="panel-body">
                        <p><b>Name:</b> {{$order->firstname}} {{$order->lastname}}</p>

                        <p><b>Address:</b> {{$order->address}}, {{$order->city}}</p>

                        <p><b>Email:</b> {{$order->email}}</p>

                        <p><b>Phone:</b> {{$order->phone}}</p>

                        <p><b>Name:</b> {{$order->additionalinfo}}</p>

                        @if($order->status == 0)
                            <div class="row">
                                <div class="col-xs-6 col-sm-6 col-md-12 col-lg-12 col-xs-offset-3 col-sm-offset-3 col-md-offset-0 col-lg-offset-0">
                                    <form method="POST" action="{{ route('order.update', $order) }}">
                                        {{ csrf_field() }}
                                        {{ method_field('PATCH') }}
                                        <button id="complete_order"
                                                class="btn btn-success btn-block">
                                            Complete
                                        </button>
                                    </form>
                                </div>
                            </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <form method="POST" action="{{ route('product.update', [$product]) }}" enctype="multipart/form-data">
            {{ csrf_field() }}
            {{ method_field('PATCH') }}
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-10 col-lg-offset-1">
                    @if($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif
                    <div class="row">
                        <div class="col-sm-12 col-sm-6 col-md-6 col-lg-6">
                            <div class="thumbnail"><img src="{{ $product->image }}"></div>
                            <div class="form-group">
                                <label for="image">Image upload</label>
                                <input type="file" class="" id="image" name="image">
                            </div>
                        </div>
                        <div class="col-sm-12 col-sm-6 col-md-6 col-lg-6">
                            <div class="form-group">
                                <label for="name">Product name</label>
                                <input type="text" class="form-control" id="name" value="{{ $product->name }}"
                                       name="name">
                            </div>
                            <div class="form-group">
                                <label for="price">Price</label>
                                <input type="text" class="form-control" id="price" value="{{ $product->price }}"
                                       name="price">
                            </div>
                            <div class="form-group">
                                <label for="description">Description</label>
                                <textarea class="form-control" rows="8" id="description" style="max-width: 100%"
                                          name="description">{{ $product->description }}</textarea>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-10 col-md-offset-1">
                    <div class="btn-toolbar">
                        <button type="submit" class="btn btn-primary btn-lg pull-right">
                            <i class="glyphicon glyphicon-save"></i> Save
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
@endsection